<?php
/** @var \Magento\Catalog\Block\Product\ListProduct $block */

$product = $block->getProduct();
?>

<div class="product attribute material">
    <?php if ($product->getAttributeText('clothing_material')): ?>
        <strong class="type">Material</strong>
        <div class="value" itemprop="material"><?php echo $product->getAttributeText('clothing_material'); ?></div>
    <?php endif; ?>
</div>
